/**
 * Scenario Candidate Discovery (CLI).
 *
 *   Process Graph + Happy Paths
 *           |
 *   discover-scenario-candidates.ts   (this script: structural, deterministic)
 *           |
 *   Candidate Scenario Inventory      (generated YAML, NOT a source of truth)
 *           |
 *   LLM / functional analysis -> human confirmation -> VARIANT / EXCEPTION / EDGE_CASE
 *
 * Finds where the Process Graph offers a transition other than the one each
 * Happy Path takes, explores each alternative until its first structural
 * outcome and writes the deduplicated result. It does NOT classify, name or
 * rank candidates and NEVER touches the scenarios YAML: a candidate is not an
 * approved Scenario. The algorithm lives in ./lib/scenario-discovery.ts.
 *
 * Usage: tsx scripts/discover-scenario-candidates.ts [process.yaml] [scenarios.yaml] [output.yaml]
 * This is generation, not validation: it is intentionally NOT part of validate:v1.3.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { pathToFileURL } from "node:url";
import { stringify } from "yaml";
import { loadYaml, type ProcessModel } from "./lib/process-model";
import type { ScenarioModel } from "./lib/scenario-model";
import {
  DEFAULT_DISCOVERY_CONFIG,
  TERMINATION_TYPES,
  discoverScenarioCandidates,
  type DiscoveryResult
} from "./lib/scenario-discovery";

const DEFAULT_PROCESS_FILE = "business/processes/repair-management-v1.3.yaml";
const DEFAULT_SCENARIOS_FILE = "business/scenarios/repair-management-scenarios-v1.3.yaml";
const DEFAULT_OUTPUT_FILE = "generated/scenarios/repair-management-candidates-v1.3.yaml";

const HEADER = [
  "# GENERATED FILE - DO NOT EDIT BY HAND.",
  "# NOT A SOURCE OF TRUTH. NOT CONFIRMED BUSINESS SCENARIOS.",
  "#",
  "# Generated by scripts/discover-scenario-candidates.ts from the Process Graph",
  "# and the Happy Paths. Each candidate is only a structural difference between",
  "# the Process Graph and a Happy Path; it is NOT classified (no VARIANT /",
  "# EXCEPTION / EDGE_CASE), NOT named and NOT an approved Scenario. Regenerate",
  "# with `npm run discover:scenarios:v1.3`; the output is deterministic.",
  ""
].join("\n");

export function renderCandidatesYaml(
  result: DiscoveryResult,
  processModel: ProcessModel,
  happyPathIds: string[]
): string {
  const document = {
    generated: {
      tool: "scripts/discover-scenario-candidates.ts",
      status: "GENERATED_NOT_SOURCE_OF_TRUTH",
      source_process: { id: processModel.process.id, version: processModel.process.version },
      happy_paths: happyPathIds,
      config: { max_depth: result.config.maxDepth },
      summary: {
        candidates_before_deduplication: result.candidatesBeforeDedup,
        unique_candidates: result.candidates.length,
        by_termination: result.terminationCounts
      }
    },
    candidates: result.candidates
  };
  return `${HEADER}${stringify(document, { lineWidth: 0, aliasDuplicateObjects: false })}`;
}

function printSummary(result: DiscoveryResult, processModel: ProcessModel, outputFile: string): void {
  console.log(`Scenario Candidate Discovery - ${processModel.process.id} V${processModel.process.version}\n`);
  console.log(`Happy Paths analyzed: ${result.perHappyPath.length}\n`);
  for (const stats of result.perHappyPath) {
    console.log(stats.happyPathId);
    console.log(`  divergence points: ${stats.divergencePoints}`);
    console.log(`  divergences found: ${stats.divergences}`);
    console.log(`  candidates before deduplication: ${stats.candidatesBeforeDedup}`);
    console.log(`  reconverging branches pruned: ${stats.prunedReconvergences}`);
  }
  console.log(`\nCandidates before deduplication: ${result.candidatesBeforeDedup}`);
  console.log(`Unique candidates: ${result.candidates.length}\n`);
  console.log("Termination (unique candidates):");
  for (const type of TERMINATION_TYPES) console.log(`  ${type}: ${result.terminationCounts[type]}`);
  console.log(`\nGenerated:\n${outputFile}`);
}

function main(): void {
  const [processFile = DEFAULT_PROCESS_FILE, scenariosFile = DEFAULT_SCENARIOS_FILE, outputFile = DEFAULT_OUTPUT_FILE] =
    process.argv.slice(2);
  const processModel = loadYaml<ProcessModel>(processFile);
  const scenariosModel = loadYaml<ScenarioModel>(scenariosFile);

  const result = discoverScenarioCandidates(processModel, scenariosModel.scenarios, DEFAULT_DISCOVERY_CONFIG);
  const happyPathIds = result.perHappyPath.map((stats) => stats.happyPathId);

  mkdirSync(dirname(outputFile), { recursive: true });
  writeFileSync(outputFile, renderCandidatesYaml(result, processModel, happyPathIds), "utf8");
  printSummary(result, processModel, outputFile);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  main();
}
