/**
 * Generates a self-contained, interactive HTML viewer for the business
 * process: the same Mermaid diagram as generate-mermaid.ts, plus a click
 * -> detail panel resolving actor, business-rule and Feature references.
 *
 * YAML remains the single source of truth. This script only reads
 * business/processes, business/actors, business/rules and business/features
 * and renders them; it never introduces new process or Feature information.
 *
 * Features are rendered as a filtering/highlighting LAYER over the existing
 * Business Process diagram (via feature.process_nodes[]), never as new
 * Mermaid nodes or a second flow: the diagram topology generated by
 * buildDiagramSource() is exactly the same with or without Features loaded.
 *
 * Mermaid is embedded inline (from node_modules/mermaid) so the generated
 * HTML also works offline, e.g. on a notebook in a meeting room with no
 * reliable network.
 *
 * All five source files are parameterizable via optional positional CLI
 * args (`tsx scripts/generate-process-viewer.ts [processFile] [rulesFile]
 * [actorsFile] [featuresFile] [scenariosFile]`), the same convention as
 * validate-references.ts, so this one script also generates the viewer
 * for a draft revision (e.g. PROC-REP V1.3, which has its own process +
 * rules files and, deliberately, no Features yet). The output filename is
 * derived from the process file's stem: the default (no args, V1.2)
 * keeps producing exactly `generated/viewer/repair-management.html` as
 * before; an explicit V1.3 process file produces a sibling
 * `repair-management-v1.3.html`. When no Features file is resolved, the
 * Feature selector/highlighting UI is omitted from the generated page
 * entirely rather than rendering an empty/broken control - the same
 * treatment applies to Scenarios via the 5th arg (there is no V1.2
 * Scenarios file yet, so V1.2 never renders that selector either).
 *
 * Scenarios (business/scenarios/*.yaml) are rendered as a SECOND,
 * mutually-exclusive highlighting layer over the exact same diagram: a
 * Scenario's PROCESS_EDGE steps reference real process.edges (never a
 * second Mermaid graph), and FUNCTIONAL_ACTION steps (transversal
 * capabilities with no node of their own, e.g. Registrar Pago) are shown
 * only in the detail panel's step list, never as a diagram line. Because
 * two edges can share the same from/to with a different condition (e.g.
 * PROC-REP-200 -> PROC-REP-210 on "Completado" vs. "Interrumpido"),
 * highlighting a Scenario's edges cannot reuse the Feature layer's
 * "both endpoints are members" heuristic: it must match the EXACT edge
 * (from + condition + to). Mermaid gives every rendered edge <path> an
 * `id="L-<from>-<to>-<n>"`, where `n` is the 0-based occurrence rank of
 * that (from,to) pair among model.edges, in array order (empirically
 * verified against mermaid 10.9.8 with a jsdom render). `withMermaidIndex()`
 * below precomputes that same rank server-side so the client can build
 * the exact id for a given step and select that one path, never its
 * parallel sibling.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import {
  buildClickDirectives,
  buildFlowchartBody,
  loadYaml,
  type Actor,
  type BusinessRule,
  type ProcessEdge,
  type ProcessModel,
  type ProcessNode,
} from "./lib/process-model";
import type { FeatureDefinition, FeatureModel, FeatureScope } from "./lib/feature-model";
import { deriveScenarioFeatures } from "./lib/feature-scenario-mapping";
import type { Scenario, ScenarioModel } from "./lib/scenario-model";

const DEFAULT_PROCESS_FILE = join("business", "processes", "repair-management.yaml");
const DEFAULT_ACTORS_FILE = join("business", "actors", "actors.yaml");
const DEFAULT_RULES_FILE = join("business", "rules", "business-rules.yaml");
const DEFAULT_FEATURES_FILE = join("business", "features", "repair-management-features.yaml");
const MERMAID_LIB_FILE = join("node_modules", "mermaid", "dist", "mermaid.min.js");

const cliArgs = process.argv.slice(2);
const isDefaultRun = cliArgs.length === 0;

const PROCESS_FILE = cliArgs[0] ?? DEFAULT_PROCESS_FILE;
const RULES_FILE = cliArgs[1] ?? DEFAULT_RULES_FILE;
const ACTORS_FILE = cliArgs[2] ?? DEFAULT_ACTORS_FILE;
// See validate-references.ts for the same convention: zero-arg run keeps
// V1.2's Features; an explicit run without a 4th/5th arg means "no
// Features/Scenarios for this revision yet", not "fall back to V1.2's".
const FEATURES_FILE: string | null = isDefaultRun ? DEFAULT_FEATURES_FILE : cliArgs[3] || null;
const SCENARIOS_FILE: string | null = isDefaultRun ? null : cliArgs[4] || null;
const OUTPUT_FILE = join("generated", "viewer", `${basename(PROCESS_FILE, ".yaml")}.html`);

const CLICK_CALLBACK = "selectNode";

type ResolvedActor = { id: string; name: string } | { id: string; missing: true };
type ResolvedRule =
  | { id: string; name: string; description?: string; status?: string }
  | { id: string; missing: true };

interface ResolvedNode {
  id: string;
  type: string;
  name: string;
  description?: string;
  actor?: ResolvedActor;
  actoresAlternativos?: ResolvedActor[];
  inputs?: string[];
  outputs?: string[];
  rules?: ResolvedRule[];
}

function resolveActor(actorId: string, actorsById: Map<string, Actor>): ResolvedActor {
  const actor = actorsById.get(actorId);
  if (!actor) {
    console.warn(`Referencia de actor no encontrada: ${actorId}`);
    return { id: actorId, missing: true };
  }
  return { id: actor.id, name: actor.name };
}

function resolveRules(ruleIds: string[], rulesById: Map<string, BusinessRule>): ResolvedRule[] {
  return ruleIds.map((ruleId) => {
    const rule = rulesById.get(ruleId);
    if (!rule) {
      console.warn(`Referencia de regla no encontrada: ${ruleId}`);
      return { id: ruleId, missing: true };
    }
    return { id: rule.id, name: rule.name, description: rule.description, status: rule.status };
  });
}

function resolveNode(
  node: ProcessNode,
  actorsById: Map<string, Actor>,
  rulesById: Map<string, BusinessRule>
): ResolvedNode {
  return {
    id: node.id,
    type: node.type,
    name: node.name,
    description: node.description,
    actor: node.actor ? resolveActor(node.actor, actorsById) : undefined,
    actoresAlternativos: node.actores_alternativos?.map((actorId) =>
      resolveActor(actorId, actorsById)
    ),
    inputs: node.inputs,
    outputs: node.outputs,
    rules: node.rules ? resolveRules(node.rules, rulesById) : undefined,
  };
}

interface ResolvedFeature {
  id: string;
  name: string;
  status: string;
  purpose: string;
  inputs: string[];
  outputs: string[];
  process_nodes: string[];
  business_rules: ResolvedRule[];
  scope: FeatureScope;
  open_questions: string[];
}

/**
 * Reuses resolveRules() as-is (it already just maps rule ids -> resolved
 * rules given any rulesById map) instead of duplicating that resolution
 * logic for Feature.business_rules[].
 */
function resolveFeature(feature: FeatureDefinition, rulesById: Map<string, BusinessRule>): ResolvedFeature {
  return {
    id: feature.id,
    name: feature.name,
    status: feature.status,
    purpose: feature.purpose,
    inputs: feature.inputs,
    outputs: feature.outputs,
    process_nodes: feature.process_nodes,
    business_rules: resolveRules(feature.business_rules, rulesById),
    scope: feature.scope,
    open_questions: feature.open_questions,
  };
}

interface ResolvedEdge extends ProcessEdge {
  /** 0-based occurrence rank of this (from,to) pair among model.edges, in array order - see the module doc comment on why the Scenario layer needs this to pick one parallel edge over another. */
  mermaidIndex: number;
}

interface ResolvedScenario extends Scenario {
  /** Precomputed via deriveScenarioFeatures() (scripts/lib/feature-scenario-mapping.ts) - the client never re-derives this. */
  active_features: string[];
  /** Why each active Feature is active (node/action that activated it), shown next to it in the panel. */
  activation_reasons: Record<string, string[]>;
  /** Diagnostic only (section 6/9): raw intersection, never rendered in the panel, kept here only in case it's useful from the browser console or a future test. */
  touched_features: string[];
}

function resolveScenario(scenario: Scenario, featuresModel: FeatureModel): ResolvedScenario {
  const { touchedFeatureIds, activeFeatureIds, activationReasons } = deriveScenarioFeatures(featuresModel, scenario);
  return {
    ...scenario,
    active_features: activeFeatureIds,
    activation_reasons: activationReasons,
    touched_features: touchedFeatureIds,
  };
}

function withMermaidIndex(edges: ProcessEdge[]): ResolvedEdge[] {
  const counts = new Map<string, number>();
  return edges.map((edge) => {
    const pairKey = `${edge.from}::${edge.to}`;
    const mermaidIndex = counts.get(pairKey) ?? 0;
    counts.set(pairKey, mermaidIndex + 1);
    return { ...edge, mermaidIndex };
  });
}

/** Prevents a literal "</script" inside generated content from closing the enclosing <script> tag. */
function embedJson(value: unknown): string {
  return JSON.stringify(value).replace(/<\/script/gi, "<\\/script");
}

/** Escapes text interpolated directly into the static HTML shell (header title/badges). */
function escapeHtmlStatic(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function buildDiagramSource(model: ProcessModel): string {
  return [
    "flowchart TD",
    ...buildFlowchartBody(model),
    "",
    ...buildClickDirectives(model.nodes, CLICK_CALLBACK),
  ].join("\n");
}

const STYLES = `
  :root {
    color-scheme: light;
    --bg: #f4f5f7;
    --surface: #ffffff;
    --border: #e5e7eb;
    --text: #1c1f27;
    --text-muted: #6b7280;
    --text-faint: #9aa1ac;
    --accent: #4f46e5;
    --accent-soft: #eef1ff;
    --accent-soft-border: #d9dcff;
    --warning-bg: #fef2f2;
    --warning-border: #fecaca;
    --warning-text: #b91c1c;
    --radius-sm: 6px;
    --radius-md: 10px;
    --radius-lg: 14px;
    --shadow-sm: 0 1px 2px rgba(16, 24, 40, 0.04), 0 1px 3px rgba(16, 24, 40, 0.06);
    --shadow-md: 0 4px 10px rgba(16, 24, 40, 0.08);
  }
  * { box-sizing: border-box; }
  html, body { height: 100%; margin: 0; }
  body {
    font-family: -apple-system, "Segoe UI Variable", "Segoe UI", system-ui, Roboto, Arial, sans-serif;
    color: var(--text);
    background: var(--bg);
    display: flex;
    flex-direction: column;
  }

  #app-header {
    flex: 0 0 auto;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 16px;
    padding: 12px 20px;
    background: var(--surface);
    border-bottom: 1px solid var(--border);
    z-index: 20;
  }
  #app-header .title { display: flex; flex-direction: column; gap: 1px; min-width: 0; }
  #app-header .eyebrow {
    font-size: 11px;
    font-weight: 600;
    letter-spacing: 0.07em;
    text-transform: uppercase;
    color: var(--accent);
  }
  #app-header h1 {
    margin: 0;
    font-size: 16px;
    font-weight: 650;
    color: var(--text);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  #app-header { flex-wrap: wrap; row-gap: 8px; }
  .search-wrap { position: relative; flex: 1 1 260px; max-width: 360px; min-width: 140px; }
  #node-search {
    width: 100%;
    font: inherit;
    font-size: 13px;
    padding: 7px 12px;
    border: 1px solid var(--border);
    border-radius: 999px;
    background: var(--bg);
    color: var(--text);
    outline: none;
  }
  #node-search:focus { border-color: var(--accent); background: var(--surface); }
  #search-results {
    position: absolute;
    top: calc(100% + 6px);
    left: 0;
    right: 0;
    max-height: 320px;
    overflow-y: auto;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: var(--radius-md);
    box-shadow: var(--shadow-md);
    z-index: 30;
    padding: 4px;
  }
  #app-header .badges { display: flex; gap: 6px; flex: 0 0 auto; }
  .badge {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    font-size: 11px;
    font-weight: 600;
    padding: 3px 9px;
    border-radius: 999px;
    background: var(--accent-soft);
    color: var(--accent);
    border: 1px solid var(--accent-soft-border);
    white-space: nowrap;
  }
  .badge.neutral { background: #f3f4f6; color: var(--text-muted); border-color: var(--border); }
  .badge.status-draft { background: #fffbeb; color: #b45309; border-color: #fde68a; }
  .badge.type-activity { background: #eef2ff; color: #4338ca; border-color: #dde1ff; }
  .badge.type-decision { background: #fff7ed; color: #c2410c; border-color: #fed7aa; }
  .badge.type-event { background: #f5f3ff; color: #6d28d9; border-color: #e5deff; }
  .badge.type-start, .badge.type-end { background: #ecfdf5; color: #047857; border-color: #a7f3d0; }
  .field > .badge { margin-top: 6px; }

  #layout { flex: 1 1 auto; display: flex; flex-direction: row; min-height: 0; }

  #diagram-pane {
    position: relative;
    flex: 1 1 auto;
    min-width: 0;
    overflow: auto;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    cursor: grab;
    background:
      radial-gradient(circle, #dfe1e7 1px, transparent 1px) 0 0 / 20px 20px,
      var(--bg);
    border-right: 1px solid var(--border);
  }
  #diagram-pane.panning { cursor: grabbing; user-select: none; }
  /* Origin top-left (not top-center): scaling from the center pushes the
     left half of a wide diagram into negative scroll space, which a
     browser can never scroll back to. With top-left, the scaled content
     only ever grows right/down, so the whole diagram stays reachable by
     scrolling/panning at any zoom. */
  #diagram-inner {
    transform-origin: 0 0;
    padding: 32px;
    width: max-content;
    flex: 0 0 auto;
  }
  /* The SVG is given its REAL pixel size (viewBox) from JS: Mermaid emits
     width="100%" plus a max-width, and inside a max-content container
     that percentage cannot resolve, so the browser collapsed a
     2868px-wide diagram to ~450px BEFORE any zoom was applied. */
  #diagram-inner svg { max-width: none !important; }
  .node.selected > * {
    stroke: var(--accent) !important;
    stroke-width: 3px !important;
    filter: drop-shadow(0 0 6px rgba(79, 70, 229, 0.45));
  }
  .node.context > * { stroke: var(--accent) !important; stroke-width: 1.5px !important; }
  .node.dimmed { opacity: 0.6; transition: opacity 0.15s ease; }
  #diagram-inner.focus-mode .node.dimmed { opacity: 0.15; }
  path.edge-context { stroke: var(--accent) !important; stroke-width: 2px !important; opacity: 1 !important; }
  path.edge-dimmed { opacity: 0.7; transition: opacity 0.15s ease; }
  #diagram-inner.focus-mode path.edge-dimmed { opacity: 0.15; }

  /* Feature layer: independent from selected/context/dimmed above (never
     removed or overridden by it). Visual hierarchy is selected > feature
     member > context > dimmed, expressed here purely via stroke-width
     (2px, between context's 1.5px and selected's 3px) so a manually
     selected node - which always also gets .selected - still reads as
     the strongest element on screen. */
  .node.feature-member > * { stroke: var(--accent) !important; stroke-width: 2px !important; }
  .node.feature-dimmed { opacity: 0.3; transition: opacity 0.15s ease; }
  path.feature-edge { stroke: var(--accent) !important; stroke-width: 2px !important; opacity: 1 !important; }
  path.feature-edge-dimmed { opacity: 0.2; transition: opacity 0.15s ease; }

  .legend-panel {
    position: sticky;
    bottom: 12px;
    align-self: flex-start;
    margin: 12px;
    width: fit-content;
    max-width: 220px;
    background: rgba(255, 255, 255, 0.92);
    backdrop-filter: blur(6px);
    border: 1px solid var(--border);
    border-radius: var(--radius-md);
    box-shadow: var(--shadow-sm);
    padding: 6px 10px;
    font-size: 12px;
    z-index: 10;
  }
  .legend-panel summary {
    cursor: pointer;
    font-weight: 600;
    color: var(--text-muted);
    list-style: none;
  }
  .legend-panel summary::-webkit-details-marker { display: none; }
  .legend-panel summary::before { content: "\\25b8  "; }
  .legend-panel[open] summary::before { content: "\\25be  "; }
  .legend-body { display: flex; flex-direction: column; gap: 5px; margin-top: 6px; }
  .legend-item { display: flex; align-items: center; gap: 7px; color: var(--text-muted); }
  .legend-swatch {
    width: 13px;
    height: 13px;
    flex: 0 0 auto;
    border: 1.5px solid var(--text-muted);
    background: var(--surface);
  }
  .legend-swatch.shape-rect { border-radius: 3px; }
  .legend-swatch.shape-diamond { width: 10px; height: 10px; border-radius: 2px; transform: rotate(45deg); }
  .legend-swatch.shape-hexagon {
    border-radius: 0;
    clip-path: polygon(25% 0%, 75% 0%, 100% 50%, 75% 100%, 25% 100%, 0% 50%);
  }
  .legend-swatch.shape-circle { border-radius: 50%; }

  #toolbar {
    position: sticky;
    align-self: flex-start;
    top: 12px;
    left: 12px;
    display: inline-flex;
    gap: 2px;
    padding: 4px;
    margin: 12px;
    width: fit-content;
    background: rgba(255, 255, 255, 0.92);
    backdrop-filter: blur(6px);
    border: 1px solid var(--border);
    border-radius: 999px;
    box-shadow: var(--shadow-sm);
    z-index: 10;
  }
  #toolbar button {
    font-size: 14px;
    font-weight: 600;
    min-width: 32px;
    padding: 6px 10px;
    cursor: pointer;
    border: none;
    background: transparent;
    color: var(--text);
    border-radius: 999px;
    transition: background 0.12s ease;
  }
  #toolbar { flex-wrap: wrap; row-gap: 4px; }
  #toolbar button:hover { background: var(--accent-soft); color: var(--accent); }
  #toolbar #zoom-reset { color: var(--text-muted); font-weight: 500; font-size: 12px; }
  #toolbar .toolbar-divider { width: 1px; align-self: stretch; background: var(--border); margin: 2px 3px; }
  #toolbar .mode-btn { font-size: 11.5px; padding: 6px 10px; color: var(--text-muted); }
  #toolbar .mode-btn.active { background: var(--accent-soft); color: var(--accent); font-weight: 600; }
  #toolbar .mode-btn:disabled { opacity: 0.4; cursor: not-allowed; }
  #toolbar .mode-btn:disabled:hover { background: transparent; color: var(--text-muted); }
  #toolbar .feature-select-label { font-size: 11.5px; color: var(--text-muted); padding: 0 2px 0 8px; }
  #toolbar #feature-select {
    font: inherit;
    font-size: 12px;
    max-width: 220px;
    padding: 5px 8px;
    border: 1px solid var(--border);
    border-radius: 999px;
    background: var(--surface);
    color: var(--text);
    cursor: pointer;
  }
  #toolbar #feature-select:focus { border-color: var(--accent); outline: none; }
  #toolbar #scenario-select {
    font: inherit;
    font-size: 12px;
    max-width: 260px;
    padding: 5px 8px;
    border: 1px solid var(--border);
    border-radius: 999px;
    background: var(--surface);
    color: var(--text);
    cursor: pointer;
  }
  #toolbar #scenario-select:focus { border-color: var(--accent); outline: none; }

  #detail-pane {
    flex: 0 0 380px;
    max-width: 42vw;
    overflow-y: auto;
    background: var(--surface);
  }
  #detail-pane .panel-inner { padding: 20px 22px; }
  #detail-pane h2 {
    font-size: 12px;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    color: var(--text-faint);
    margin: 0 0 16px;
    font-weight: 700;
  }
  .field { margin-bottom: 18px; }
  .field-label {
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--text-faint);
    margin-bottom: 3px;
    font-weight: 600;
  }
  .field-value { font-size: 14.5px; line-height: 1.5; color: var(--text); }
  .field-value.big { font-size: 19px; font-weight: 650; line-height: 1.3; }
  .field-sub { font-size: 12px; color: var(--text-muted); margin-top: 1px; }
  .field ul { margin: 4px 0 0; padding-left: 18px; }
  .field li { font-size: 14px; margin-bottom: 3px; color: var(--text); }
  .hint { font-size: 13px; color: var(--text-muted); line-height: 1.5; }
  .divider { border: none; border-top: 1px solid var(--border); margin: 18px 0; }
  .warning {
    font-size: 13px;
    color: var(--warning-text);
    background: var(--warning-bg);
    border: 1px solid var(--warning-border);
    border-radius: var(--radius-sm);
    padding: 7px 10px;
  }
  .rule-card {
    border: 1px solid var(--border);
    border-left: 3px solid var(--accent);
    border-radius: var(--radius-sm);
    padding: 9px 11px;
    margin-bottom: 8px;
    background: #fafafe;
  }
  .rule-card.warning { background: var(--warning-bg); border-color: var(--warning-border); border-left-color: var(--warning-text); }
  .rule-id { font-size: 11px; font-weight: 700; color: var(--accent); letter-spacing: 0.02em; }
  .rule-name { font-size: 14px; font-weight: 650; margin: 3px 0 4px; color: var(--text); }
  .rule-desc { font-size: 13px; color: var(--text-muted); margin-bottom: 6px; line-height: 1.45; }
  .rule-status { font-size: 10.5px; color: var(--text-faint); text-transform: uppercase; letter-spacing: 0.04em; font-weight: 600; }

  .nav-list { display: flex; flex-direction: column; gap: 6px; }
  .nav-card, .search-result {
    display: block;
    width: 100%;
    text-align: left;
    background: none;
    border: 1px solid transparent;
    border-radius: var(--radius-sm);
    padding: 7px 9px;
    cursor: pointer;
    font: inherit;
    color: inherit;
  }
  .nav-card:hover, .nav-card:focus-visible,
  .search-result:hover, .search-result:focus-visible {
    background: var(--accent-soft);
    border-color: var(--accent-soft-border);
    outline: none;
  }
  .nav-card .nav-id, .search-result .nav-id { font-size: 11px; color: var(--text-faint); margin-top: 2px; }
  .nav-card .nav-name, .search-result .nav-name { font-size: 13.5px; font-weight: 600; color: var(--text); }
  .nav-card .nav-condition {
    display: inline-block;
    font-size: 10.5px;
    font-weight: 600;
    color: var(--text-muted);
    background: var(--accent-soft);
    border-radius: 999px;
    padding: 1px 8px;
    margin-top: 5px;
  }
  .nav-card .nav-condition-value {
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.03em;
    color: var(--accent);
  }
  .decision-list .nav-condition { font-size: 12px; padding: 2px 10px; }
  .nav-empty { margin: 0; }
  .search-empty { padding: 8px 9px; font-size: 13px; color: var(--text-muted); }

  .scope-sublabel {
    font-size: 11px;
    font-weight: 700;
    color: var(--text-faint);
    text-transform: uppercase;
    letter-spacing: 0.04em;
    margin: 10px 0 3px;
  }
  .scope-sublabel:first-child { margin-top: 0; }
  .open-questions-box {
    background: #f8f9fb;
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    padding: 9px 12px;
    font-size: 13px;
    color: var(--text-muted);
  }
  .open-questions-box ul { margin: 0; padding-left: 18px; }
  .open-questions-box li { margin-bottom: 4px; }
  .open-questions-box li:last-child { margin-bottom: 0; }

  /* Scenario facts/expected: a stable key-value list (section 14), reused
     identically for facts and expected since both are the same
     key/label/value shape. */
  .fact-list { display: flex; flex-direction: column; gap: 2px; }
  .fact-row {
    display: flex;
    justify-content: space-between;
    gap: 12px;
    padding: 5px 0;
    border-bottom: 1px solid var(--border);
    font-size: 13.5px;
  }
  .fact-row:last-child { border-bottom: none; }
  .fact-label { color: var(--text-muted); }
  .fact-value { color: var(--text); font-weight: 600; text-align: right; }

  /* FUNCTIONAL_ACTION step card: visually distinct from a PROCESS_EDGE
     nav-card (dashed border, no hover/click affordance) since it never
     corresponds to a diagram node - it is purely informational. */
  .nav-card.functional-action {
    cursor: default;
    border-style: dashed;
    border-color: var(--accent-soft-border);
    background: var(--accent-soft);
  }
  .nav-card.functional-action .nav-id { color: var(--accent); font-weight: 700; }
  .nav-card .nav-desc-plain { font-size: 12.5px; color: var(--text-muted); margin-top: 4px; line-height: 1.4; }
  .nav-card.functional-action .nav-desc { font-size: 12.5px; color: var(--text-muted); margin-top: 4px; line-height: 1.4; }

  #diagram-pane::-webkit-scrollbar, #detail-pane::-webkit-scrollbar { width: 10px; height: 10px; }
  #diagram-pane::-webkit-scrollbar-thumb, #detail-pane::-webkit-scrollbar-thumb {
    background: #d3d5db; border-radius: 999px; border: 2px solid transparent; background-clip: content-box;
  }

  @media (max-width: 800px) {
    #layout { flex-direction: column; }
    #diagram-pane { height: 52vh; border-right: none; border-bottom: 1px solid var(--border); }
    #detail-pane { flex: 1 1 auto; max-width: 100%; }
    #app-header .badges { flex-wrap: wrap; justify-content: flex-end; }
    .search-wrap { flex: 1 1 100%; max-width: none; order: 3; }
  }
`;

const CLIENT_SCRIPT = `
  var CURRENT_SELECTED_ID = null;
  var ACTIVE_FEATURE_ID = null;
  // Named generically ("scenario", not "happyPath") so a future EXCEPTION/
  // VARIANT/EDGE_CASE scenario can reuse this same state and rendering
  // path without a rewrite - only the "Happy Path" label in the UI is
  // specific to today, because HAPPY_PATH is the only type that exists.
  var ACTIVE_SCENARIO_ID = null;

  var TYPE_LABELS = { event: "Evento", activity: "Actividad", decision: "Decision", start: "Inicio", end: "Fin" };
  var TYPE_SHAPES = { event: "shape-hexagon", activity: "shape-rect", decision: "shape-diamond", start: "shape-circle", end: "shape-circle" };

  function typeLabel(type) {
    return TYPE_LABELS[type] || type;
  }

  function escapeHtml(text) {
    return String(text)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
  }

  function renderList(label, items) {
    if (!items || items.length === 0) return "";
    var lis = items.map(function (item) { return "<li>" + escapeHtml(item) + "</li>"; }).join("");
    return '<div class="field"><div class="field-label">' + label + '</div><ul>' + lis + "</ul></div>";
  }

  function renderActor(actor) {
    if (!actor) return "";
    if (actor.missing) {
      return '<div class="field"><div class="field-label">Actor</div>' +
        '<div class="warning">Actor no encontrado: ' + escapeHtml(actor.id) + "</div></div>";
    }
    return '<div class="field"><div class="field-label">Actor</div>' +
      '<div class="field-value">' + escapeHtml(actor.name) + "</div>" +
      '<div class="field-sub">' + escapeHtml(actor.id) + "</div></div>";
  }

  function renderActoresAlternativos(actores) {
    if (!actores || actores.length === 0) return "";
    var items = actores.map(function (actor) {
      if (actor.missing) {
        return '<div class="warning">Actor no encontrado: ' +
          escapeHtml(actor.id) + "</div>";
      }
      return '<div class="field-value">' + escapeHtml(actor.name) + "</div>" +
        '<div class="field-sub">' + escapeHtml(actor.id) + "</div>";
    }).join("");
    return '<div class="field"><div class="field-label">' +
      "Tambien autorizado</div>" + items + "</div>";
  }

  function renderRules(rules) {
    if (!rules || rules.length === 0) return "";
    var cards = rules.map(function (rule) {
      if (rule.missing) {
        return '<div class="rule-card warning">Regla no encontrada: ' + escapeHtml(rule.id) + "</div>";
      }
      var desc = rule.description ? '<div class="rule-desc">' + escapeHtml(rule.description) + "</div>" : "";
      var status = rule.status ? '<div class="rule-status">Status: ' + escapeHtml(rule.status) + "</div>" : "";
      return '<div class="rule-card"><div class="rule-id">' + escapeHtml(rule.id) + "</div>" +
        '<div class="rule-name">' + escapeHtml(rule.name) + "</div>" + desc + status + "</div>";
    }).join("");
    return '<div class="field"><div class="field-label">Reglas</div>' + cards + "</div>";
  }

  // Same card renderer as renderRules(), but a Feature with business_rules:
  // [] gets a discreet explanatory line instead of silently showing
  // nothing (section 16 of the request).
  function renderFeatureRules(rules) {
    if (!rules || rules.length === 0) {
      return '<div class="field"><div class="field-label">Reglas</div>' +
        '<p class="hint">Sin reglas de negocio asociadas directamente.</p></div>';
    }
    return renderRules(rules);
  }

  function renderScope(scope) {
    if (!scope) return "";
    var includes = scope.includes && scope.includes.length
      ? '<div class="scope-sublabel">Incluye</div><ul>' +
          scope.includes.map(function (item) { return "<li>" + escapeHtml(item) + "</li>"; }).join("") +
        "</ul>"
      : "";
    var excludes = scope.excludes && scope.excludes.length
      ? '<div class="scope-sublabel">Excluye</div><ul>' +
          scope.excludes.map(function (item) { return "<li>" + escapeHtml(item) + "</li>"; }).join("") +
        "</ul>"
      : "";
    if (!includes && !excludes) return "";
    return '<div class="field"><div class="field-label">Scope</div>' + includes + excludes + "</div>";
  }

  // Neutral box on purpose (section 15): open questions are deliberately
  // pending validation, not an error - so they never use the red
  // "referencia faltante" warning style.
  function renderOpenQuestions(questions) {
    if (!questions || questions.length === 0) return "";
    var items = questions.map(function (q) { return "<li>" + escapeHtml(q) + "</li>"; }).join("");
    return '<div class="field"><div class="field-label">Preguntas abiertas</div>' +
      '<div class="open-questions-box"><ul>' + items + "</ul></div></div>";
  }

  // --- Node <-> Feature (built by inverting feature.process_nodes[]) -----
  // Map<nodeId, Set<featureId>> - never Map<nodeId, featureId>: a node can
  // legitimately belong to N Features. Built once, lazily, straight from
  // FEATURES_BY_ID; adding a FEAT-REP-008 to the YAML and regenerating
  // needs no change here.
  var NODE_FEATURES_INDEX = null;

  function buildNodeFeaturesIndex() {
    var index = new Map();
    Object.keys(FEATURES_BY_ID).forEach(function (featureId) {
      FEATURES_BY_ID[featureId].process_nodes.forEach(function (nodeId) {
        if (!index.has(nodeId)) index.set(nodeId, new Set());
        index.get(nodeId).add(featureId);
      });
    });
    return index;
  }

  function getFeaturesForNode(nodeId) {
    if (!NODE_FEATURES_INDEX) NODE_FEATURES_INDEX = buildNodeFeaturesIndex();
    var owners = NODE_FEATURES_INDEX.get(nodeId);
    return owners ? Array.from(owners) : [];
  }

  function renderNodeFeatures(nodeId) {
    var featureIds = getFeaturesForNode(nodeId);
    if (!featureIds.length) return "";
    var cards = featureIds.map(function (featureId) {
      var feature = FEATURES_BY_ID[featureId];
      var name = feature ? feature.name : featureId;
      return '<button type="button" class="nav-card" data-nav-feature="' + escapeHtml(featureId) + '">' +
        '<div class="nav-name">' + escapeHtml(name) + "</div>" +
        '<div class="nav-id">' + escapeHtml(featureId) + "</div>" +
        "</button>";
    }).join("");
    return '<div class="field"><div class="field-label">Features relacionadas</div>' +
      '<div class="nav-list">' + cards + "</div></div>";
  }

  // --- Scenarios (Happy Path layer) ---------------------------------------
  // A Scenario never duplicates the Business Process: PROCESS_EDGE steps
  // reference real edges (matched here the same way, from+condition+to),
  // and FUNCTIONAL_ACTION steps are shown only in this panel, never as a
  // diagram line.

  function isProcessEdgeStep(step) { return step.kind === "PROCESS_EDGE"; }
  function isFunctionalActionStep(step) { return step.kind === "FUNCTIONAL_ACTION"; }

  function formatFactValue(value) {
    if (typeof value === "boolean") return value ? "Si" : "No";
    return String(value);
  }

  function renderFacts(label, facts) {
    if (!facts || !facts.length) return "";
    var rows = facts.map(function (fact) {
      return '<div class="fact-row"><span class="fact-label">' + escapeHtml(fact.label) + "</span>" +
        '<span class="fact-value">' + escapeHtml(formatFactValue(fact.value)) + "</span></div>";
    }).join("");
    return '<div class="field"><div class="field-label">' + label + '</div><div class="fact-list">' + rows + "</div></div>";
  }

  /** Every node touched by a Scenario's PROCESS_EDGE steps (from and to), as a lookup set. */
  function getScenarioTouchedNodes(scenario) {
    var set = {};
    scenario.steps.forEach(function (step) {
      if (isProcessEdgeStep(step)) {
        set[step.from] = true;
        set[step.to] = true;
      }
    });
    return set;
  }

  /**
   * Renders scenario.active_features - the Features genuinely
   * functionally involved, precomputed server-side by
   * deriveScenarioFeatures() (scripts/lib/feature-scenario-mapping.ts) so
   * this ALWAYS/CONTEXTUAL-aware logic lives in exactly one place, not
   * reimplemented in client JS. scenario.touched_features (the raw, less
   * precise intersection) travels with the same embedded data for
   * diagnostics but is deliberately never shown here (section 9).
   */
  function renderScenarioFeatures(featureIds, reasonsById) {
    if (!featureIds || !featureIds.length) {
      return '<div class="field"><div class="field-label">Features involucradas</div>' +
        '<p class="hint">Ninguna Feature funcionalmente activa para este Scenario.</p></div>';
    }
    var cards = featureIds.map(function (featureId) {
      var feature = FEATURES_BY_ID[featureId];
      var name = feature ? feature.name : featureId;
      var why = reasonsById && reasonsById[featureId] && reasonsById[featureId].length
        ? '<div class="nav-desc-plain">Activa por: ' + escapeHtml(reasonsById[featureId].join("; ")) + "</div>"
        : "";
      return '<button type="button" class="nav-card" data-nav-feature="' + escapeHtml(featureId) + '">' +
        '<div class="nav-name">' + escapeHtml(name) + "</div>" +
        '<div class="nav-id">' + escapeHtml(featureId) + "</div>" +
        why +
        "</button>";
    }).join("");
    return '<div class="field"><div class="field-label">Features involucradas</div>' +
      '<div class="nav-list">' + cards + "</div></div>";
  }

  /** Finds the exact process edge a PROCESS_EDGE step refers to (from + condition + to), never just from/to. */
  function findMatchingEdge(step) {
    for (var i = 0; i < EDGES.length; i++) {
      var edge = EDGES[i];
      if (edge.from === step.from && edge.to === step.to && (edge.condition || "") === (step.condition || "")) {
        return edge;
      }
    }
    return null;
  }

  /** Mirrors the id Mermaid assigns the rendered <path> - see the module doc comment in generate-process-viewer.ts. */
  function edgeElementId(edge) {
    return "L-" + edge.from + "-" + edge.to + "-" + edge.mermaidIndex;
  }

  function getScenarioMatchedEdgeIds(scenario) {
    var ids = {};
    scenario.steps.forEach(function (step) {
      if (!isProcessEdgeStep(step)) return;
      var edge = findMatchingEdge(step);
      if (edge) ids[edgeElementId(edge)] = true;
    });
    return ids;
  }

  function renderScenarioSteps(steps) {
    var items = steps.map(function (step) {
      if (isProcessEdgeStep(step)) {
        var fromNode = NODES_BY_ID[step.from];
        var toNode = NODES_BY_ID[step.to];
        var fromName = fromNode ? fromNode.name : step.from;
        var toName = toNode ? toNode.name : step.to;
        var condition = step.condition
          ? '<div class="nav-condition">Condicion: <span class="nav-condition-value">' + escapeHtml(step.condition) + "</span></div>"
          : "";
        return '<button type="button" class="nav-card" data-nav-node="' + escapeHtml(step.to) + '">' +
          '<div class="nav-name">' + escapeHtml(fromName) + " &rarr; " + escapeHtml(toName) + "</div>" +
          '<div class="nav-id">' + escapeHtml(step.from) + " -&gt; " + escapeHtml(step.to) + "</div>" +
          condition +
          "</button>";
      }
      if (isFunctionalActionStep(step)) {
        var desc = step.description ? '<div class="nav-desc">' + escapeHtml(step.description) + "</div>" : "";
        return '<div class="nav-card functional-action">' +
          '<div class="nav-id">Accion funcional &middot; ' + escapeHtml(step.feature) + "</div>" +
          '<div class="nav-name">' + escapeHtml(step.name) + "</div>" +
          desc +
          "</div>";
      }
      return "";
    }).join("");
    return '<div class="field"><div class="field-label">Recorrido</div><div class="nav-list">' + items + "</div></div>";
  }

  // Nodes this Scenario deliberately does NOT traverse, each with its reason
  // (documentary: the path itself is always driven by steps).
  function renderSkippedNodes(skipped) {
    if (!skipped || !skipped.length) return "";
    var cards = skipped.map(function (item) {
      var node = NODES_BY_ID[item.node];
      var name = node ? node.name : item.node;
      return '<button type="button" class="nav-card" data-nav-node="' + escapeHtml(item.node) + '">' +
        '<div class="nav-name">' + escapeHtml(name) + "</div>" +
        '<div class="nav-id">' + escapeHtml(item.node) + "</div>" +
        '<div class="nav-desc-plain">' + escapeHtml(item.reason) + "</div>" +
        "</button>";
    }).join("");
    return '<div class="field"><div class="field-label">Nodos omitidos</div>' +
      '<div class="nav-list">' + cards + "</div></div>";
  }

  // Panel order (section 14, plus a final derived section): ID/Nombre/
  // Tipo/Scope/Status/Descripcion, Condiciones del Happy Path (facts),
  // Recorrido (steps), Resultado esperado (expected), Features
  // involucradas (active_features - derived, shown last on purpose to
  // read as computed information, not part of the Scenario's own
  // authored definition).
  function renderScenarioDetail(scenarioId) {
    var scenario = SCENARIOS_BY_ID[scenarioId];
    if (!scenario) return;

    var html = "<h2>Happy Path</h2>" +
      '<div class="field"><div class="field-value big">' + escapeHtml(scenario.name) + "</div>" +
      '<span class="badge status-' + escapeHtml(scenario.status) + '">' + escapeHtml(scenario.status) + "</span></div>" +
      '<div class="field"><div class="field-label">ID</div><div class="field-value">' + escapeHtml(scenario.id) + "</div></div>" +
      '<div class="field"><div class="field-label">Tipo</div><div class="field-value">' + escapeHtml(scenario.type) + "</div></div>" +
      '<div class="field"><div class="field-label">Scope</div><div class="field-value">' + escapeHtml(scenario.scope) + "</div></div>" +
      (scenario.description ? '<div class="field"><div class="field-label">Descripcion</div><div class="field-value">' + escapeHtml(scenario.description) + "</div></div>" : "") +
      '<hr class="divider">' +
      renderFacts("Condiciones del Happy Path", scenario.facts) +
      '<hr class="divider">' +
      renderScenarioSteps(scenario.steps) +
      (scenario.skipped_nodes && scenario.skipped_nodes.length
        ? '<hr class="divider">' + renderSkippedNodes(scenario.skipped_nodes)
        : "") +
      '<hr class="divider">' +
      renderFacts("Resultado esperado", scenario.expected) +
      '<hr class="divider">' +
      renderScenarioFeatures(scenario.active_features, scenario.activation_reasons);

    panelBody().innerHTML = html;
  }

  // --- Navigation derived from EDGES (never duplicated by hand) ----------
  // "Llega desde" and "Continua hacia" are computed straight from EDGES on
  // every render: incoming = EDGES where edge.to === nodeId, outgoing =
  // EDGES where edge.from === nodeId. Nothing about the graph is hardcoded.

  function getIncomingEdges(nodeId) {
    return EDGES.filter(function (edge) { return edge.to === nodeId; });
  }

  function getOutgoingEdges(nodeId) {
    return EDGES.filter(function (edge) { return edge.from === nodeId; });
  }

  function renderNavCard(edge, direction) {
    var otherId = direction === "in" ? edge.from : edge.to;
    var otherNode = NODES_BY_ID[otherId];
    var name = otherNode ? otherNode.name : otherId;
    var condition = edge.condition
      ? '<div class="nav-condition">Condicion: <span class="nav-condition-value">' + escapeHtml(edge.condition) + "</span></div>"
      : "";
    return '<button type="button" class="nav-card" data-nav-node="' + escapeHtml(otherId) + '">' +
      '<div class="nav-name">' + escapeHtml(name) + "</div>" +
      '<div class="nav-id">' + escapeHtml(otherId) + "</div>" +
      condition +
      "</button>";
  }

  function renderNavSection(title, edges, direction, extraListClass) {
    var emptyText = direction === "in" ? "Sin conexiones entrantes." : "Sin conexiones salientes.";
    var body = edges.length
      ? '<div class="nav-list' + (extraListClass ? " " + extraListClass : "") + '">' +
          edges.map(function (edge) { return renderNavCard(edge, direction); }).join("") +
        "</div>"
      : '<p class="hint nav-empty">' + emptyText + "</p>";
    return '<div class="field"><div class="field-label">' + title + "</div>" + body + "</div>";
  }

  function panelBody() {
    return document.querySelector("#detail-pane .panel-inner");
  }

  function renderProcessSummary() {
    var p = PROCESS_INFO;
    var html = '<h2>Proceso</h2>' +
      '<div class="field"><div class="field-value big">' + escapeHtml(p.name) + "</div></div>" +
      '<div class="field"><div class="field-label">ID</div><div class="field-value">' + escapeHtml(p.id) + "</div></div>" +
      '<div class="field"><div class="field-label">Version</div><div class="field-value">' + escapeHtml(p.version) + "</div></div>" +
      (p.status ? '<div class="field"><div class="field-label">Status</div><div class="field-value">' + escapeHtml(p.status) + "</div></div>" : "") +
      '<hr class="divider">' +
      '<p class="hint">Seleccione un nodo del proceso, o use el buscador, para ver su detalle.</p>';
    panelBody().innerHTML = html;
  }

  // Panel order: Nombre, ID+tipo, Actor, Descripcion, navegacion (Llega
  // desde / Continua hacia), Inputs, Outputs, Business Rules. Para nodos
  // decision, "Continua hacia" se muestra primero porque son sus
  // alternativas de decision.
  function renderNodeDetail(nodeId) {
    var node = NODES_BY_ID[nodeId];
    if (!node) return;

    var incoming = getIncomingEdges(nodeId);
    var outgoing = getOutgoingEdges(nodeId);
    var isDecision = node.type === "decision";

    var incomingSection = renderNavSection("Llega desde", incoming, "in");
    var outgoingSection = renderNavSection("Continua hacia", outgoing, "out", isDecision ? "decision-list" : "");
    var navigation = isDecision ? outgoingSection + incomingSection : incomingSection + outgoingSection;

    var html = "<h2>Detalle del nodo</h2>" +
      '<div class="field"><div class="field-value big">' + escapeHtml(node.name) + "</div>" +
      '<span class="badge type-' + escapeHtml(node.type) + '">' + escapeHtml(typeLabel(node.type)) + "</span></div>" +
      '<div class="field"><div class="field-label">ID</div><div class="field-value">' + escapeHtml(node.id) + "</div></div>" +
      '<hr class="divider">' +
      renderActor(node.actor) +
      renderActoresAlternativos(node.actoresAlternativos) +
      (node.description ? '<div class="field"><div class="field-label">Descripcion</div><div class="field-value">' + escapeHtml(node.description) + "</div></div>" : "") +
      '<hr class="divider">' +
      navigation +
      '<hr class="divider">' +
      renderList("Inputs", node.inputs) +
      renderList("Outputs", node.outputs) +
      renderRules(node.rules) +
      renderNodeFeatures(nodeId);
    panelBody().innerHTML = html;
  }

  // Panel order (section 8): Feature/ID/Name/Status, Purpose, Inputs,
  // Outputs, Business Rules, Scope, Open Questions, Process Nodes.
  function renderFeatureDetail(featureId) {
    var feature = FEATURES_BY_ID[featureId];
    if (!feature) return;

    var processNodesBody = feature.process_nodes.length
      ? '<div class="nav-list">' +
          feature.process_nodes.map(function (nodeId) {
            var node = NODES_BY_ID[nodeId];
            var name = node ? node.name : nodeId;
            return '<button type="button" class="nav-card" data-nav-node="' + escapeHtml(nodeId) + '">' +
              '<div class="nav-name">' + escapeHtml(name) + "</div>" +
              '<div class="nav-id">' + escapeHtml(nodeId) + "</div>" +
              "</button>";
          }).join("") +
        "</div>"
      : '<p class="hint nav-empty">Sin process_nodes.</p>';

    var html = "<h2>Feature</h2>" +
      '<div class="field"><div class="field-value big">' + escapeHtml(feature.name) + "</div>" +
      '<span class="badge status-' + escapeHtml(feature.status) + '">' + escapeHtml(feature.status) + "</span></div>" +
      '<div class="field"><div class="field-label">ID</div><div class="field-value">' + escapeHtml(feature.id) + "</div></div>" +
      '<hr class="divider">' +
      '<div class="field"><div class="field-label">Purpose</div><div class="field-value">' + escapeHtml(feature.purpose) + "</div></div>" +
      renderList("Inputs", feature.inputs) +
      renderList("Outputs", feature.outputs) +
      renderFeatureRules(feature.business_rules) +
      '<hr class="divider">' +
      renderScope(feature.scope) +
      renderOpenQuestions(feature.open_questions) +
      '<hr class="divider">' +
      '<div class="field"><div class="field-label">Process Nodes</div>' + processNodesBody + "</div>";

    panelBody().innerHTML = html;
  }

  // --- Highlight of the selected node's immediate context -----------------
  // Every node/edge in the rendered SVG gets exactly one of: selected,
  // context (direct predecessor/successor) or dimmed. Predecessors and
  // successors share one "context" style on purpose (kept to a single
  // accent color throughout, per the minimal/professional look this
  // viewer aims for) - direction is still conveyed by the arrowheads and
  // by the "Llega desde" / "Continua hacia" sections themselves.

  /** Reads the real node ids a rendered edge path connects, from its own
   * "LS-<from>"/"LE-<to>" classes (see highlight comment above) - used to
   * decide whether an edge sits entirely inside the active Feature. */
  function getEdgeEndpoints(edgeEl) {
    var from = null;
    var to = null;
    edgeEl.classList.forEach(function (cls) {
      if (cls.indexOf("LS-") === 0) from = cls.slice(3);
      else if (cls.indexOf("LE-") === 0) to = cls.slice(3);
    });
    return { from: from, to: to };
  }

  function clearHighlightClasses(nodeEls, edgeEls) {
    for (var i = 0; i < nodeEls.length; i++) {
      nodeEls[i].classList.remove("selected", "context", "dimmed", "feature-member", "feature-dimmed");
    }
    for (var j = 0; j < edgeEls.length; j++) {
      edgeEls[j].classList.remove("edge-context", "edge-dimmed", "feature-edge", "feature-edge-dimmed");
    }
  }

  /**
   * Recomputes every node/edge highlight class from three independent
   * pieces of state: CURRENT_SELECTED_ID, ACTIVE_FEATURE_ID and
   * ACTIVE_SCENARIO_ID. Visual hierarchy: selected > layer member (Feature
   * or Scenario) > context > dimmed. Feature and Scenario are mutually
   * exclusive (activateFeature()/activateScenario() enforce that), so at
   * most one of the two branches below ever runs.
   *
   * When neither is active this is byte-for-byte the original node-context
   * behavior (section 11: no Feature selected must not change existing
   * navigation at all). When a layer is active, node context
   * (predecessor/successor highlighting) is not computed - the layer's own
   * membership highlighting takes over that role instead, to keep the
   * modes simple and non-overlapping. Feature and Scenario reuse the same
   * "feature-*" CSS classes on purpose: they are the same visual treatment
   * (a highlighted subset of the diagram), never shown at the same time.
   */
  function applyHighlight() {
    var container = document.getElementById("diagram-inner");
    var nodeEls = container.querySelectorAll(".node");
    var edgeEls = container.querySelectorAll("path.flowchart-link");
    clearHighlightClasses(nodeEls, edgeEls);

    if (ACTIVE_FEATURE_ID) {
      var feature = FEATURES_BY_ID[ACTIVE_FEATURE_ID];
      var memberSet = {};
      (feature ? feature.process_nodes : []).forEach(function (id) { memberSet[id] = true; });

      for (var a = 0; a < nodeEls.length; a++) {
        var nodeEl = nodeEls[a];
        var nodeId = nodeEl.getAttribute("data-id");
        if (nodeId === CURRENT_SELECTED_ID) {
          nodeEl.classList.add("selected");
        } else if (memberSet[nodeId]) {
          nodeEl.classList.add("feature-member");
        } else {
          nodeEl.classList.add("feature-dimmed");
        }
      }

      for (var b = 0; b < edgeEls.length; b++) {
        var edgeEl = edgeEls[b];
        var endpoints = getEdgeEndpoints(edgeEl);
        var bothMembers = endpoints.from && endpoints.to && memberSet[endpoints.from] && memberSet[endpoints.to];
        edgeEl.classList.add(bothMembers ? "feature-edge" : "feature-edge-dimmed");
      }
      return;
    }

    if (ACTIVE_SCENARIO_ID) {
      var scenario = SCENARIOS_BY_ID[ACTIVE_SCENARIO_ID];
      var touchedNodes = scenario ? getScenarioTouchedNodes(scenario) : {};
      var matchedEdgeIds = scenario ? getScenarioMatchedEdgeIds(scenario) : {};

      for (var e = 0; e < nodeEls.length; e++) {
        var scenarioNodeEl = nodeEls[e];
        var scenarioNodeId = scenarioNodeEl.getAttribute("data-id");
        if (scenarioNodeId === CURRENT_SELECTED_ID) {
          scenarioNodeEl.classList.add("selected");
        } else if (touchedNodes[scenarioNodeId]) {
          scenarioNodeEl.classList.add("feature-member");
        } else {
          scenarioNodeEl.classList.add("feature-dimmed");
        }
      }

      // Identified by from + condition + to (its rendered id), never by
      // endpoints alone: two edges can share the same from/to with a
      // different condition (see the module doc comment).
      for (var f = 0; f < edgeEls.length; f++) {
        var scenarioEdgeEl = edgeEls[f];
        var isMatched = matchedEdgeIds[scenarioEdgeEl.getAttribute("id")];
        scenarioEdgeEl.classList.add(isMatched ? "feature-edge" : "feature-edge-dimmed");
      }
      return;
    }

    if (!CURRENT_SELECTED_ID) return;

    var contextIds = {};
    getIncomingEdges(CURRENT_SELECTED_ID).forEach(function (edge) { contextIds[edge.from] = true; });
    getOutgoingEdges(CURRENT_SELECTED_ID).forEach(function (edge) { contextIds[edge.to] = true; });

    for (var c = 0; c < nodeEls.length; c++) {
      var el = nodeEls[c];
      var id = el.getAttribute("data-id");
      if (id === CURRENT_SELECTED_ID) {
        el.classList.add("selected");
      } else if (contextIds[id]) {
        el.classList.add("context");
      } else {
        el.classList.add("dimmed");
      }
    }

    for (var d = 0; d < edgeEls.length; d++) {
      var edgeEl2 = edgeEls[d];
      var touches = edgeEl2.classList.contains("LS-" + CURRENT_SELECTED_ID) || edgeEl2.classList.contains("LE-" + CURRENT_SELECTED_ID);
      edgeEl2.classList.add(touches ? "edge-context" : "edge-dimmed");
    }
  }

  window.selectNode = function (nodeId) {
    CURRENT_SELECTED_ID = nodeId;
    renderNodeDetail(nodeId);
    applyHighlight();
    var focusBtn = document.getElementById("mode-focus");
    if (focusBtn) focusBtn.disabled = false;
  };

  // Used by direct diagram clicks (no scrolling - the user already sees
  // the node they clicked). Search results and "Llega desde" / "Continua
  // hacia" cards use navigateToNode below instead, which also centers it.
  function navigateToNode(nodeId) {
    window.selectNode(nodeId);
    centerNodeInView(nodeId);
  }

  // activeFeatureId is intentionally a state separate from
  // CURRENT_SELECTED_ID (section 10): selecting a Feature does not clear
  // the current node selection, and clicking a node does not clear the
  // active Feature. Activating a Feature DOES clear an active Scenario
  // (and vice versa, see activateScenario()): only one functional
  // highlighting layer is active at a time, to avoid confusing overlapping
  // layers on the diagram.
  function activateFeature(featureId) {
    ACTIVE_FEATURE_ID = featureId || null;
    var select = document.getElementById("feature-select");
    if (select && select.value !== (ACTIVE_FEATURE_ID || "")) select.value = ACTIVE_FEATURE_ID || "";

    if (ACTIVE_FEATURE_ID) {
      ACTIVE_SCENARIO_ID = null;
      var scenarioSelectToClear = document.getElementById("scenario-select");
      if (scenarioSelectToClear) scenarioSelectToClear.value = "";
      renderFeatureDetail(ACTIVE_FEATURE_ID);
    } else if (CURRENT_SELECTED_ID) {
      renderNodeDetail(CURRENT_SELECTED_ID);
    } else {
      renderProcessSummary();
    }

    applyHighlight();

    if (ACTIVE_FEATURE_ID && FEATURES_BY_ID[ACTIVE_FEATURE_ID]) {
      centerNodes(FEATURES_BY_ID[ACTIVE_FEATURE_ID].process_nodes);
    }
  }

  function wireFeatureSelect() {
    // Omitted entirely for a process revision with no Features yet (e.g.
    // a draft under review, see featureSelectorMarkup in buildHtml()).
    var select = document.getElementById("feature-select");
    if (!select) return;
    select.addEventListener("change", function (event) {
      activateFeature(event.target.value || null);
    });
  }

  // Mirrors activateFeature() above; see that function's comment for the
  // mutual-exclusion rule.
  function activateScenario(scenarioId) {
    ACTIVE_SCENARIO_ID = scenarioId || null;
    var select = document.getElementById("scenario-select");
    if (select && select.value !== (ACTIVE_SCENARIO_ID || "")) select.value = ACTIVE_SCENARIO_ID || "";

    if (ACTIVE_SCENARIO_ID) {
      ACTIVE_FEATURE_ID = null;
      var featureSelectToClear = document.getElementById("feature-select");
      if (featureSelectToClear) featureSelectToClear.value = "";
      renderScenarioDetail(ACTIVE_SCENARIO_ID);
    } else if (CURRENT_SELECTED_ID) {
      renderNodeDetail(CURRENT_SELECTED_ID);
    } else {
      renderProcessSummary();
    }

    applyHighlight();

    if (ACTIVE_SCENARIO_ID && SCENARIOS_BY_ID[ACTIVE_SCENARIO_ID]) {
      centerNodes(Object.keys(getScenarioTouchedNodes(SCENARIOS_BY_ID[ACTIVE_SCENARIO_ID])));
    }
  }

  function wireScenarioSelect() {
    // Omitted entirely when this revision has no Scenarios yet (e.g. V1.2
    // today, see scenarioSelectorMarkup in buildHtml()).
    var select = document.getElementById("scenario-select");
    if (!select) return;
    select.addEventListener("change", function (event) {
      activateScenario(event.target.value || null);
    });
  }

  function wireDetailNavigation() {
    document.getElementById("detail-pane").addEventListener("click", function (event) {
      var nodeTarget = event.target.closest("[data-nav-node]");
      if (nodeTarget) {
        navigateToNode(nodeTarget.getAttribute("data-nav-node"));
        return;
      }
      var featureTarget = event.target.closest("[data-nav-feature]");
      if (featureTarget) {
        activateFeature(featureTarget.getAttribute("data-nav-feature"));
      }
    });
  }

  // --- Centering -----------------------------------------------------------
  // Scrolls #diagram-pane so the combined bounding box of the given nodes
  // ends up roughly centered, without touching the current zoom level.
  // getBoundingClientRect() already reflects the current CSS transform
  // scale, so the delta between the target center and the pane's center
  // works at any zoom.
  function centerNodes(nodeIds) {
    var pane = document.getElementById("diagram-pane");
    if (!pane) return;

    var rects = nodeIds
      .map(function (id) { return document.querySelector('#diagram-inner [data-id="' + id + '"]'); })
      .filter(Boolean)
      .map(function (el) { return el.getBoundingClientRect(); });
    if (!rects.length) return;

    var left = Math.min.apply(null, rects.map(function (r) { return r.left; }));
    var right = Math.max.apply(null, rects.map(function (r) { return r.right; }));
    var top = Math.min.apply(null, rects.map(function (r) { return r.top; }));
    var bottom = Math.max.apply(null, rects.map(function (r) { return r.bottom; }));

    var paneRect = pane.getBoundingClientRect();
    var deltaX = (left + right) / 2 - (paneRect.left + paneRect.width / 2);
    var deltaY = (top + bottom) / 2 - (paneRect.top + paneRect.height / 2);

    pane.scrollBy({ left: deltaX, top: deltaY, behavior: "smooth" });
  }

  function centerNodeInView(nodeId) {
    centerNodes([nodeId]);
  }

  function wireCenterButton() {
    document.getElementById("center-btn").addEventListener("click", function () {
      if (CURRENT_SELECTED_ID) centerNodeInView(CURRENT_SELECTED_ID);
    });
  }

  // --- Fullscreen ------------------------------------------------------------
  function wireFullscreen() {
    var btn = document.getElementById("fullscreen-btn");
    if (!document.documentElement.requestFullscreen) {
      btn.hidden = true;
      return;
    }
    btn.addEventListener("click", function () {
      if (document.fullscreenElement) {
        document.exitFullscreen();
      } else {
        document.documentElement.requestFullscreen();
      }
    });
    document.addEventListener("fullscreenchange", function () {
      var active = Boolean(document.fullscreenElement);
      btn.textContent = active ? "⛶ Salir de pantalla completa" : "⛶ Pantalla completa";
      btn.setAttribute("aria-pressed", active ? "true" : "false");
    });
  }

  // --- Modo foco -------------------------------------------------------------
  // Purely visual: reuses the same selected/context/dimmed classes that
  // applyHighlight() already assigns, just intensifies the "dimmed" opacity
  // via the .focus-mode modifier class (see CSS). No new grafo, no data
  // change - only a viewing preference. Independent from the Feature layer:
  // focus-mode only ever targets .dimmed, which applyHighlight() never sets
  // while a Feature is active (it uses .feature-dimmed instead).
  function setFocusMode(active) {
    document.getElementById("diagram-inner").classList.toggle("focus-mode", active);
    var fullBtn = document.getElementById("mode-full");
    var focusBtn = document.getElementById("mode-focus");
    fullBtn.classList.toggle("active", !active);
    focusBtn.classList.toggle("active", active);
    fullBtn.setAttribute("aria-pressed", active ? "false" : "true");
    focusBtn.setAttribute("aria-pressed", active ? "true" : "false");
  }

  function wireFocusToggle() {
    document.getElementById("mode-full").addEventListener("click", function () { setFocusMode(false); });
    document.getElementById("mode-focus").addEventListener("click", function () {
      if (document.getElementById("mode-focus").disabled) return;
      setFocusMode(true);
    });
  }

  // --- Buscador de nodos -------------------------------------------------
  // Simple case-insensitive substring match over id/name, no fuzzy search.
  function closeSearchResults() {
    var results = document.getElementById("search-results");
    results.hidden = true;
    results.innerHTML = "";
  }

  function renderSearchResults(matches) {
    var results = document.getElementById("search-results");
    if (!matches.length) {
      results.innerHTML = '<div class="search-empty">Sin resultados.</div>';
    } else {
      results.innerHTML = matches.map(function (node) {
        return '<button type="button" class="search-result" data-nav-node="' + escapeHtml(node.id) + '">' +
          '<div class="nav-id">' + escapeHtml(node.id) + "</div>" +
          '<div class="nav-name">' + escapeHtml(node.name) + "</div>" +
          "</button>";
      }).join("");
    }
    results.hidden = false;
  }

  function wireSearch() {
    var input = document.getElementById("node-search");
    var results = document.getElementById("search-results");

    input.addEventListener("input", function () {
      var query = input.value.trim().toLowerCase();
      if (!query) { closeSearchResults(); return; }
      var matches = Object.keys(NODES_BY_ID)
        .map(function (id) { return NODES_BY_ID[id]; })
        .filter(function (node) {
          return node.id.toLowerCase().indexOf(query) !== -1 || node.name.toLowerCase().indexOf(query) !== -1;
        })
        .slice(0, 20);
      renderSearchResults(matches);
    });

    input.addEventListener("keydown", function (event) {
      if (event.key === "Escape") {
        input.value = "";
        closeSearchResults();
        input.blur();
      }
    });

    // Delay so a click on a result (which also blurs the input) still
    // registers before the dropdown disappears.
    input.addEventListener("blur", function () { setTimeout(closeSearchResults, 150); });

    results.addEventListener("click", function (event) {
      var target = event.target.closest("[data-nav-node]");
      if (!target) return;
      var nodeId = target.getAttribute("data-nav-node");
      input.value = "";
      closeSearchResults();
      navigateToNode(nodeId);
    });
  }

  // --- Leyenda -------------------------------------------------------------
  // Derived from the types actually present in NODES_BY_ID - never assumes
  // "start" exists just because the schema allows it.
  function renderLegend() {
    var present = {};
    Object.keys(NODES_BY_ID).forEach(function (id) { present[NODES_BY_ID[id].type] = true; });
    var order = ["start", "event", "activity", "decision", "end"];
    var body = document.getElementById("legend-body");
    body.innerHTML = order
      .filter(function (type) { return present[type]; })
      .map(function (type) {
        var shape = TYPE_SHAPES[type] || "shape-rect";
        return '<div class="legend-item"><span class="legend-swatch ' + shape + '"></span>' + typeLabel(type) + "</div>";
      })
      .join("");
  }

  // --- Zoom / pan -----------------------------------------------------------
  // Design (section 9): the diagram is shown at its natural, readable size
  // (scale 1 = Mermaid's own font size) instead of being shrunk to fit the
  // viewport, and the user navigates a large diagram by panning. Zoom is
  // multiplicative (each step x1.25) because the useful range is very wide:
  // an additive step is either glacial at 8x or a jump at 0.2x.
  var ZOOM_MIN = 0.15;
  var ZOOM_MAX = 8;
  var ZOOM_STEP = 1.25;
  var INITIAL_SCALE = 1;
  var CURRENT_SCALE = 1;

  /** Gives the rendered SVG its real pixel size from its viewBox (see the CSS note on #diagram-inner svg). */
  function sizeSvgToViewBox() {
    var svg = document.querySelector("#diagram-inner svg");
    if (!svg) return null;
    var vb = svg.viewBox && svg.viewBox.baseVal;
    if (!vb || !vb.width || !vb.height) return null;
    svg.removeAttribute("width");
    svg.style.width = vb.width + "px";
    svg.style.height = vb.height + "px";
    return { width: vb.width, height: vb.height };
  }

  function clampScale(value) {
    return Math.min(ZOOM_MAX, Math.max(ZOOM_MIN, value));
  }

  /**
   * Applies a new scale keeping the content point under (anchorX, anchorY)
   * - pane-relative pixels; defaults to the pane center - fixed on screen.
   */
  function setScale(nextScale, anchorX, anchorY) {
    var pane = document.getElementById("diagram-pane");
    var target = document.getElementById("diagram-inner");
    var resetBtn = document.getElementById("zoom-reset");
    var next = clampScale(nextScale);
    var ax = anchorX === undefined ? pane.clientWidth / 2 : anchorX;
    var ay = anchorY === undefined ? pane.clientHeight / 2 : anchorY;
    var contentX = (pane.scrollLeft + ax) / CURRENT_SCALE;
    var contentY = (pane.scrollTop + ay) / CURRENT_SCALE;
    CURRENT_SCALE = next;
    target.style.transform = "scale(" + next + ")";
    pane.scrollLeft = contentX * next - ax;
    pane.scrollTop = contentY * next - ay;
    resetBtn.textContent = Math.round(next * 100) + "%";
  }

  function initZoom() {
    var pane = document.getElementById("diagram-pane");
    var size = sizeSvgToViewBox();
    CURRENT_SCALE = INITIAL_SCALE;
    document.getElementById("diagram-inner").style.transform = "scale(" + INITIAL_SCALE + ")";
    document.getElementById("zoom-reset").textContent = Math.round(INITIAL_SCALE * 100) + "%";
    // Start horizontally centered on the diagram; vertically at its top.
    if (size) pane.scrollLeft = Math.max(0, (size.width * INITIAL_SCALE + 64 - pane.clientWidth) / 2);
    pane.scrollTop = 0;

    document.getElementById("zoom-in").addEventListener("click", function () { setScale(CURRENT_SCALE * ZOOM_STEP); });
    document.getElementById("zoom-out").addEventListener("click", function () { setScale(CURRENT_SCALE / ZOOM_STEP); });
    document.getElementById("zoom-reset").addEventListener("click", function () { setScale(INITIAL_SCALE); });

    // Ctrl/Cmd + wheel (and trackpad pinch, which browsers report as ctrl+wheel)
    // zooms around the cursor; a plain wheel keeps scrolling/panning natively.
    pane.addEventListener("wheel", function (event) {
      if (!event.ctrlKey && !event.metaKey) return;
      event.preventDefault();
      var rect = pane.getBoundingClientRect();
      var factor = event.deltaY < 0 ? ZOOM_STEP : 1 / ZOOM_STEP;
      setScale(CURRENT_SCALE * factor, event.clientX - rect.left, event.clientY - rect.top);
    }, { passive: false });

    // Drag-to-pan on the background. A move under 4px is still a click, so
    // node clicks, toolbar buttons and the legend keep working untouched.
    var drag = null;
    var suppressClick = false;
    pane.addEventListener("mousedown", function (event) {
      if (event.button !== 0) return;
      if (event.target.closest("#toolbar, .legend-panel")) return;
      drag = { x: event.clientX, y: event.clientY, left: pane.scrollLeft, top: pane.scrollTop, moved: false };
    });
    window.addEventListener("mousemove", function (event) {
      if (!drag) return;
      var dx = event.clientX - drag.x;
      var dy = event.clientY - drag.y;
      if (!drag.moved && Math.abs(dx) < 4 && Math.abs(dy) < 4) return;
      drag.moved = true;
      pane.classList.add("panning");
      pane.scrollLeft = drag.left - dx;
      pane.scrollTop = drag.top - dy;
    });
    window.addEventListener("mouseup", function () {
      if (drag && drag.moved) {
        suppressClick = true;
        setTimeout(function () { suppressClick = false; }, 0);
      }
      drag = null;
      pane.classList.remove("panning");
    });
    pane.addEventListener("click", function (event) {
      if (suppressClick) {
        event.stopPropagation();
        event.preventDefault();
      }
    }, true);
  }

  document.addEventListener("DOMContentLoaded", function () {
    mermaid.initialize({ startOnLoad: false, securityLevel: "loose", theme: "default" });
    mermaid.render("processDiagram", DIAGRAM_SOURCE).then(function (result) {
      var container = document.getElementById("diagram-inner");
      container.innerHTML = result.svg;
      if (result.bindFunctions) result.bindFunctions(container);
      initZoom();
    });
    renderProcessSummary();
    renderLegend();
    wireDetailNavigation();
    wireCenterButton();
    wireFullscreen();
    wireFocusToggle();
    wireSearch();
    wireFeatureSelect();
    wireScenarioSelect();
  });
`;

function buildHtml(
  model: ProcessModel,
  resolvedNodes: ResolvedNode[],
  resolvedFeatures: ResolvedFeature[],
  scenarios: ResolvedScenario[],
  mermaidLib: string
): string {
  const nodesById: Record<string, ResolvedNode> = {};
  for (const node of resolvedNodes) {
    nodesById[node.id] = node;
  }

  const featuresById: Record<string, ResolvedFeature> = {};
  for (const feature of resolvedFeatures) {
    featuresById[feature.id] = feature;
  }

  const scenariosById: Record<string, ResolvedScenario> = {};
  for (const scenario of scenarios) {
    scenariosById[scenario.id] = scenario;
  }

  const diagramSource = buildDiagramSource(model);
  // Passed through with one derived field added (mermaidIndex - see the
  // module doc comment) so the viewer's "Llega desde" / "Continua hacia"
  // navigation and the Scenario edge-highlighting layer can both work
  // entirely client-side, without a second pass over the process file.
  const edges = withMermaidIndex(model.edges);

  // Options only - never assume how many Features exist or which ids they
  // have; regenerating after a FEAT-REP-008 is added just adds an <option>.
  // The whole selector is omitted below when this revision has no
  // Features yet (e.g. a draft process version), instead of rendering an
  // empty/pointless dropdown.
  const featureOptions = resolvedFeatures
    .map(
      (feature) =>
        `<option value="${escapeHtmlStatic(feature.id)}">${escapeHtmlStatic(feature.id)} · ${escapeHtmlStatic(feature.name)}</option>`
    )
    .join("\n        ");

  const featureSelectorMarkup =
    resolvedFeatures.length > 0
      ? `<span class="toolbar-divider" aria-hidden="true"></span>
        <label class="feature-select-label" for="feature-select">Vista:</label>
        <select id="feature-select" title="Filtrar el diagrama por Feature">
          <option value="">Todas las Features</option>
        ${featureOptions}
        </select>`
      : "";

  // Same convention as featureOptions above. Labeled "Happy Path" because
  // HAPPY_PATH is the only Scenario type that exists today (section 12);
  // the underlying state/markup is generic enough to later show every
  // Scenario type without a rewrite.
  const scenarioOptions = scenarios
    .map(
      (scenario) =>
        `<option value="${escapeHtmlStatic(scenario.id)}">${escapeHtmlStatic(scenario.id)} · ${escapeHtmlStatic(scenario.name)}</option>`
    )
    .join("\n        ");

  const scenarioSelectorMarkup =
    scenarios.length > 0
      ? `<span class="toolbar-divider" aria-hidden="true"></span>
        <label class="feature-select-label" for="scenario-select">Happy Path:</label>
        <select id="scenario-select" title="Resaltar un Happy Path">
          <option value="">Proceso completo</option>
        ${scenarioOptions}
        </select>`
      : "";

  const sourceLines = [PROCESS_FILE, ACTORS_FILE, RULES_FILE, FEATURES_FILE, SCENARIOS_FILE]
    .filter((file): file is string => Boolean(file))
    .map((file) => `  - ${file.replace(/\\/g, "/")}`)
    .join("\n");

  return `<!--
  AUTO-GENERATED FILE.
  DO NOT EDIT MANUALLY.
  SOURCE:
${sourceLines}
-->
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${model.process.name} - Viewer</title>
<style>${STYLES}</style>
</head>
<body>
  <header id="app-header">
    <div class="title">
      <span class="eyebrow">Rosario Tecno · RMA</span>
      <h1>${escapeHtmlStatic(model.process.name)}</h1>
    </div>
    <div class="search-wrap">
      <input id="node-search" type="text" placeholder="Buscar nodo..." autocomplete="off" spellcheck="false">
      <div id="search-results" hidden></div>
    </div>
    <div class="badges">
      <span class="badge neutral">${escapeHtmlStatic(model.process.id)}</span>
      <span class="badge neutral">v${escapeHtmlStatic(model.process.version)}</span>
      ${model.process.status ? `<span class="badge status-${escapeHtmlStatic(model.process.status)}">${escapeHtmlStatic(model.process.status)}</span>` : ""}
    </div>
  </header>
  <div id="layout">
    <div id="diagram-pane">
      <div id="toolbar">
        <button id="zoom-out" type="button" title="Alejar">-</button>
        <button id="zoom-reset" type="button" title="Restablecer zoom">100%</button>
        <button id="zoom-in" type="button" title="Acercar">+</button>
        <span class="toolbar-divider" aria-hidden="true"></span>
        <button id="center-btn" type="button" title="Centrar en el nodo seleccionado">Centrar</button>
        <button id="fullscreen-btn" type="button" title="Pantalla completa">⛶ Pantalla completa</button>
        <span class="toolbar-divider" aria-hidden="true"></span>
        <button id="mode-full" type="button" class="mode-btn active" aria-pressed="true">Contexto completo</button>
        <button id="mode-focus" type="button" class="mode-btn" aria-pressed="false" disabled title="Seleccione un nodo para habilitar el modo foco">Modo foco</button>
        ${[featureSelectorMarkup, scenarioSelectorMarkup].filter(Boolean).join("\n        ")}
      </div>
      <div id="diagram-inner">Cargando diagrama...</div>
      <details id="legend" class="legend-panel">
        <summary>Leyenda</summary>
        <div id="legend-body" class="legend-body"></div>
      </details>
    </div>
    <div id="detail-pane"><div class="panel-inner"></div></div>
  </div>
  <script>${mermaidLib}</script>
  <script>
    var PROCESS_INFO = ${embedJson(model.process)};
    var NODES_BY_ID = ${embedJson(nodesById)};
    var EDGES = ${embedJson(edges)};
    var FEATURES_BY_ID = ${embedJson(featuresById)};
    var SCENARIOS_BY_ID = ${embedJson(scenariosById)};
    var DIAGRAM_SOURCE = ${embedJson(diagramSource)};
    ${CLIENT_SCRIPT}
  </script>
</body>
</html>
`;
}

function main(): void {
  const model = loadYaml<ProcessModel>(PROCESS_FILE);
  const actors = loadYaml<{ actors: Actor[] }>(ACTORS_FILE).actors;
  const rules = loadYaml<{ rules: BusinessRule[] }>(RULES_FILE).rules;
  const featuresModel: FeatureModel = FEATURES_FILE ? loadYaml<FeatureModel>(FEATURES_FILE) : { process: model.process, features: [] };
  const scenarios = SCENARIOS_FILE ? loadYaml<ScenarioModel>(SCENARIOS_FILE).scenarios : [];

  const actorsById = new Map(actors.map((actor) => [actor.id, actor]));
  const rulesById = new Map(rules.map((rule) => [rule.id, rule]));

  const resolvedNodes = model.nodes.map((node) => resolveNode(node, actorsById, rulesById));
  const resolvedFeatures = featuresModel.features.map((feature) => resolveFeature(feature, rulesById));
  // active_features/touched_features (section 7) computed once here, using
  // the SAME helper validate-references.ts and validate-scenarios.ts use,
  // so this never drifts into a second, viewer-only implementation.
  const resolvedScenarios = scenarios.map((scenario) => resolveScenario(scenario, featuresModel));
  const mermaidLib = readFileSync(MERMAID_LIB_FILE, "utf8");

  const html = buildHtml(model, resolvedNodes, resolvedFeatures, resolvedScenarios, mermaidLib);

  mkdirSync(dirname(OUTPUT_FILE), { recursive: true });
  writeFileSync(OUTPUT_FILE, html, "utf8");

  console.log(`Process viewer generated: ${OUTPUT_FILE}`);
}

main();
